version: '3.8'

services:

  nginx:
    environment:
      - VIRTUAL_PORT=80
      - VIRTUAL_HOST=adminer.example.com
    networks:
      - adminer-proxy
      - nginx-proxy

networks:
  adminer-proxy:
    name: adminer-proxy
  nginx-proxy:
    external:
      name: nginx-proxy